export * from './languageActions';
export * from './repoActions';
export const CONSTANTS = {
    SEARCH_REPO: 'SEARCH_REPO',
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',
    FETCH_DATA_REQUEST: 'FETCH_DATA_REQUEST',
    FETCH_DATA_SUCCESS: 'FETCH_DATA_SUCCESS',
    FETCH_DATA_FAILURE: 'FETCH_DATA_FAILURE',
    CLEAR_ERROR_AND_DATA: 'CLEAR_ERROR_AND_DATA',
};
